"use client";

import { useEffect, useState } from "react";
import Image from "next/image";
import { LANGUAGES, useLanguage } from "@/lib/i18n";
import { externalLinkProps } from "@/lib/links";
import { useCaseLinks, type GroupedCaseLink } from "@/lib/useSiteContent";
import { hamburgerHomeLabel, caseLabels } from "@/content/translations";

// Mirrors the header from the original AS studio homepage
// (原型教學轉code/design_handoff_architecture_site/建築事務所首頁.dc.html),
// minus the search box, mobile layout, and dark/light-mode toggle per
// explicit request — this site only ever renders the "dark mode" look
// (white text), so those values are just hardcoded instead of branching on
// isDarkMode/isMobile like the original. The header element itself still
// has no background of its own — only the left (menu+logo) and right
// (nav pill) groups have their own glassmorphism boxes behind them.
const basePath = process.env.NEXT_PUBLIC_BASE_PATH || "";

// The hamburger menu is just "原型首頁" (fixed — it's the nav link back to
// the main site, not a case) followed by whatever cases currently exist in
// the Internal-Pages admin's 建築案例 tab. That list comes from
// useCaseLinks() below (content/site/case-links.json, regenerated by the
// admin on every case save/delete) — there's no separate menu-editing
// screen, adding/removing a case there is the only thing that changes this
// menu. FALLBACK_CASE_LINKS is only used before that fetch resolves or if
// it ever fails, so the menu never blanks out on a network hiccup; keep it
// roughly in sync with reality but it doesn't need to be exact.
const HOME_LINK = { label: hamburgerHomeLabel, href: "https://www.as-structure.com/" };
// Ordered and flagged the same way useCaseLinks() groups the live data —
// chapter-restore's cases, then chapter-exhibit's, then chapter-detail's —
// so the divider styling below looks right even before the live fetch
// resolves, not just after. Labels reuse the exact same caseLabels entries
// as the CASES-band cards for these same 6 cases (see translations.ts), so
// they're already fully localized rather than fixed Chinese.
const FALLBACK_CASE_LINKS: GroupedCaseLink[] = [
  {
    label: caseLabels["restore-xinyi"],
    href: "https://as-studio001.github.io/Internal-Pages/?case=laogu-fang",
    isGroupStart: false,
    chNumber: "CH 1.1",
  },
  {
    label: caseLabels["restore-woodyard"],
    href: "https://as-studio001.github.io/Internal-Pages/?case=chiayi-experimental-woodyard",
    isGroupStart: false,
    chNumber: "CH 1.2",
  },
  {
    label: caseLabels["restore-office"],
    href: "https://www.mashup.com.tw/as%20studio/?page=product_shop&p_id=506003",
    isGroupStart: false,
    chNumber: "CH 1.3",
  },
  {
    label: caseLabels["exhibit-tnhs"],
    href: "https://www.tnhs.com.tw/",
    isGroupStart: true,
    chNumber: "CH 2.1",
  },
  {
    label: caseLabels["detail-proto1"],
    href: "https://asstudio029.wixsite.com/ashouse1",
    isGroupStart: true,
    chNumber: "CH 3.1",
  },
  {
    label: caseLabels["detail-yizai"],
    href: "https://www.mashup.com.tw/as%20studio/?page=product_shop&p_id=609194",
    isGroupStart: false,
    chNumber: "CH 3.2",
  },
];

export default function Header() {
  const [showMaterialMenu, setShowMaterialMenu] = useState(false);
  const [showLanguageMenu, setShowLanguageMenu] = useState(false);
  const { lang, setLang } = useLanguage();
  const liveCaseLinks = useCaseLinks();
  const materialLinks: GroupedCaseLink[] = [
    { ...HOME_LINK, isGroupStart: false },
    ...(liveCaseLinks && liveCaseLinks.length ? liveCaseLinks : FALLBACK_CASE_LINKS),
  ];

  // Same click-outside-closes behavior as the original (document listener
  // checking closest("[data-menu-box]") / closest("[data-lang-menu-box]")).
  useEffect(() => {
    const onClick = (e: MouseEvent) => {
      const target = e.target as HTMLElement;
      if (!target.closest("[data-menu-box]")) setShowMaterialMenu(false);
      if (!target.closest("[data-lang-menu-box]")) setShowLanguageMenu(false);
    };
    document.addEventListener("click", onClick);
    return () => document.removeEventListener("click", onClick);
  }, []);

  return (
    <header
      className="fixed top-0 right-0 left-0 z-[1000] flex items-center justify-between"
      style={{ padding: "24px 40px" }}
    >
      <div
        className="flex items-center gap-5 rounded-lg backdrop-blur-md"
        style={{
          padding: "16px 24px",
          backgroundColor: "oklch(0.15 0 0 / 0.15)",
        }}
      >
        <div data-menu-box className="relative">
          <button
            type="button"
            aria-label="材料選單"
            onClick={() => setShowMaterialMenu((v) => !v)}
            className="flex h-9 w-9 cursor-pointer flex-col items-center justify-center gap-[5px]"
          >
            <span className="block h-[2px] w-[22px] bg-white" />
            <span className="block h-[2px] w-[22px] bg-white" />
            <span className="block h-[2px] w-[22px] bg-white" />
          </button>
          {showMaterialMenu && (
            <div
              data-menu-box
              // w-max (not a fixed w-40 like before) — the box always
              // sizes itself to whatever its widest current row actually
              // needs, so no label (in any language, current or future
              // case) can ever wrap, per explicit request. min-w-40 keeps
              // it from looking cramped when every label happens to be
              // short.
              className="absolute top-full left-0 mt-2 w-max min-w-40 overflow-hidden rounded-lg border shadow-[0_8px_24px_rgba(0,0,0,0.2)]"
              style={{
                backgroundColor: "oklch(0.12 0 0)",
                borderColor: "oklch(0.25 0 0)",
              }}
            >
              {materialLinks.map((m, i) => {
                const isLast = i === materialLinks.length - 1;
                // A case right before a new chapter's group gets a
                // brighter divider than the plain 1px line between cases
                // of the same chapter — that's the only place this
                // stronger line shows up, per explicit request for a
                // clearer boundary between each chapter's own cases.
                // Thickness halved (was 2px) per follow-up request — still
                // distinguished from the regular 1px line by color alone.
                const nextStartsNewGroup = materialLinks[i + 1]?.isGroupStart;
                return (
                  <a
                    key={`${m.href}-${i}`}
                    href={m.href}
                    onClick={() => setShowMaterialMenu(false)}
                    {...externalLinkProps(m.href)}
                    // whitespace-nowrap — paired with the container's
                    // w-max above, this is what actually guarantees no
                    // wrapping: forces this row's own content onto one
                    // line, which is what forces the container to grow
                    // wide enough to fit it instead of wrapping.
                    className="block px-4 py-3 text-sm whitespace-nowrap text-white transition-colors hover:bg-white/10"
                    style={
                      isLast
                        ? undefined
                        : nextStartsNewGroup
                          ? { borderBottom: "1px solid oklch(0.45 0 0)" }
                          : { borderBottom: "1px solid oklch(0.2 0 0)" }
                    }
                  >
                    {/* Thin grey "CH {chapter}.{item}" tag ahead of the
                        label — only cases have one (HOME_LINK and any
                        case-links.json entry that couldn't be matched to a
                        chapter don't), per explicit request. */}
                    {m.chNumber && (
                      <span className="mr-2 text-[11px] font-light text-white/40">
                        {m.chNumber}
                      </span>
                    )}
                    {m.label[lang] ?? m.label["zh-Hant"]}
                  </a>
                );
              })}
            </div>
          )}
        </div>
        <a href="https://www.as-structure.com/" className="flex items-center gap-3">
          <Image
            src={`${basePath}/favicon-logo.png`}
            alt="原型結構 as.studio"
            width={256}
            height={256}
            className="h-9 w-9"
            priority
          />
          <span
            className="text-base text-white"
            style={{
              fontFamily: "var(--font-noto-serif-tc), 'Source Han Serif TC', serif",
              letterSpacing: "0.1em",
            }}
          >
            原型建築
          </span>
        </a>
      </div>

      <div
        className="flex items-center rounded-lg"
        style={{
          gap: "32px",
          padding: "16px 24px",
          backgroundColor: "oklch(0.15 0 0 / 0.15)",
        }}
      >
        <div data-lang-menu-box className="relative">
          <button
            type="button"
            aria-label="切換語言"
            onClick={() => setShowLanguageMenu((v) => !v)}
            className="flex h-9 w-9 cursor-pointer items-center justify-center text-white"
          >
            <svg
              width="20"
              height="20"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <circle cx="12" cy="12" r="10" />
              <line x1="2" y1="12" x2="22" y2="12" />
              <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
            </svg>
          </button>
          {showLanguageMenu && (
            <div
              data-lang-menu-box
              className="absolute top-full right-0 mt-2 min-w-[140px] overflow-hidden rounded-lg border shadow-[0_8px_24px_rgba(0,0,0,0.2)]"
              style={{
                backgroundColor: "oklch(0.12 0 0)",
                borderColor: "oklch(0.25 0 0)",
              }}
            >
              {LANGUAGES.map((l) => (
                <button
                  key={l.code}
                  type="button"
                  onClick={() => {
                    setLang(l.code);
                    setShowLanguageMenu(false);
                  }}
                  className="block w-full px-3.5 py-2.5 text-left text-[13px] text-white transition-colors hover:bg-white/10"
                  style={{ fontWeight: lang === l.code ? 700 : 400 }}
                >
                  {l.label}
                </button>
              ))}
            </div>
          )}
        </div>
      </div>
    </header>
  );
}
